# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/uP/uP.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uP || ORIG_REF_NAME==uP} -quiet] -quiet

# IP: bd/uP/ip/uP_clk_wiz_0_0/uP_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uP_clk_wiz_0_0 || ORIG_REF_NAME==uP_clk_wiz_0_0} -quiet] -quiet

# IP: bd/uP/ip/uP_microblaze_0_0/uP_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uP_microblaze_0_0 || ORIG_REF_NAME==uP_microblaze_0_0} -quiet] -quiet

# IP: bd/uP/ip/uP_dlmb_v10_1/uP_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uP_dlmb_v10_1 || ORIG_REF_NAME==uP_dlmb_v10_1} -quiet] -quiet

# IP: bd/uP/ip/uP_ilmb_v10_1/uP_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uP_ilmb_v10_1 || ORIG_REF_NAME==uP_ilmb_v10_1} -quiet] -quiet

# IP: bd/uP/ip/uP_dlmb_bram_if_cntlr_1/uP_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uP_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==uP_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/uP/ip/uP_ilmb_bram_if_cntlr_1/uP_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uP_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==uP_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/uP/ip/uP_lmb_bram_1/uP_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uP_lmb_bram_1 || ORIG_REF_NAME==uP_lmb_bram_1} -quiet] -quiet

# IP: bd/uP/ip/uP_xbar_1/uP_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uP_xbar_1 || ORIG_REF_NAME==uP_xbar_1} -quiet] -quiet

# IP: bd/uP/ip/uP_microblaze_0_axi_periph_1/uP_microblaze_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uP_microblaze_0_axi_periph_1 || ORIG_REF_NAME==uP_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/uP/ip/uP_microblaze_0_axi_intc_1/uP_microblaze_0_axi_intc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uP_microblaze_0_axi_intc_1 || ORIG_REF_NAME==uP_microblaze_0_axi_intc_1} -quiet] -quiet

# IP: bd/uP/ip/uP_microblaze_0_xlconcat_1/uP_microblaze_0_xlconcat_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uP_microblaze_0_xlconcat_1 || ORIG_REF_NAME==uP_microblaze_0_xlconcat_1} -quiet] -quiet

# IP: bd/uP/ip/uP_mdm_1_1/uP_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uP_mdm_1_1 || ORIG_REF_NAME==uP_mdm_1_1} -quiet] -quiet

# IP: bd/uP/ip/uP_rst_mig_7series_0_83M_1/uP_rst_mig_7series_0_83M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uP_rst_mig_7series_0_83M_1 || ORIG_REF_NAME==uP_rst_mig_7series_0_83M_1} -quiet] -quiet

# IP: bd/uP/ip/uP_axi_uartlite_0_0/uP_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uP_axi_uartlite_0_0 || ORIG_REF_NAME==uP_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/uP/ip/uP_axi_dma_0_0/uP_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uP_axi_dma_0_0 || ORIG_REF_NAME==uP_axi_dma_0_0} -quiet] -quiet

# IP: bd/uP/ip/uP_axis_data_fifo_0_0/uP_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uP_axis_data_fifo_0_0 || ORIG_REF_NAME==uP_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/uP/ip/uP_mig_7series_0_2/uP_mig_7series_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uP_mig_7series_0_2 || ORIG_REF_NAME==uP_mig_7series_0_2} -quiet] -quiet

# IP: bd/uP/ip/uP_auto_pc_3/uP_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uP_auto_pc_3 || ORIG_REF_NAME==uP_auto_pc_3} -quiet] -quiet

# IP: bd/uP/ip/uP_auto_us_0/uP_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uP_auto_us_0 || ORIG_REF_NAME==uP_auto_us_0} -quiet] -quiet

# IP: bd/uP/ip/uP_auto_us_1/uP_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uP_auto_us_1 || ORIG_REF_NAME==uP_auto_us_1} -quiet] -quiet

# IP: bd/uP/ip/uP_auto_us_2/uP_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uP_auto_us_2 || ORIG_REF_NAME==uP_auto_us_2} -quiet] -quiet

# IP: bd/uP/ip/uP_auto_us_3/uP_auto_us_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uP_auto_us_3 || ORIG_REF_NAME==uP_auto_us_3} -quiet] -quiet

# IP: bd/uP/ip/uP_auto_ds_0/uP_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uP_auto_ds_0 || ORIG_REF_NAME==uP_auto_ds_0} -quiet] -quiet

# IP: bd/uP/ip/uP_auto_pc_0/uP_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uP_auto_pc_0 || ORIG_REF_NAME==uP_auto_pc_0} -quiet] -quiet

# IP: bd/uP/ip/uP_auto_ds_1/uP_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uP_auto_ds_1 || ORIG_REF_NAME==uP_auto_ds_1} -quiet] -quiet

# IP: bd/uP/ip/uP_auto_pc_1/uP_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uP_auto_pc_1 || ORIG_REF_NAME==uP_auto_pc_1} -quiet] -quiet

# IP: bd/uP/ip/uP_auto_ds_2/uP_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uP_auto_ds_2 || ORIG_REF_NAME==uP_auto_ds_2} -quiet] -quiet

# IP: bd/uP/ip/uP_auto_pc_2/uP_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uP_auto_pc_2 || ORIG_REF_NAME==uP_auto_pc_2} -quiet] -quiet

# XDC: bd/uP/uP_ooc.xdc
