# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config  -id {Vivado 12-3563}  -string {{ERROR: [Vivado 12-3563] The Nested sub-design 'C:/Users/asus/PROCOM2020/RUN/PROCOM_FP/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_mig_7series_0_0/uP_mig_7series_0_0.xci' can only be generated by its parent sub-design.}}  -suppress 
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.cache/wt [current_project]
set_property parent.project_path C:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/hdl/uP_wrapper.v
add_files C:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/uP.bd
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_clk_wiz_0_0/uP_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_clk_wiz_0_0/uP_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_clk_wiz_0_0/uP_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_microblaze_0_0/uP_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_microblaze_0_0/uP_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_microblaze_0_0/uP_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_dlmb_v10_1/uP_dlmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_dlmb_v10_1/uP_dlmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_ilmb_v10_1/uP_ilmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_ilmb_v10_1/uP_ilmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_dlmb_bram_if_cntlr_1/uP_dlmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_ilmb_bram_if_cntlr_1/uP_ilmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_lmb_bram_1/uP_lmb_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_xbar_1/uP_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_microblaze_0_axi_intc_1/uP_microblaze_0_axi_intc_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_microblaze_0_axi_intc_1/uP_microblaze_0_axi_intc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_microblaze_0_axi_intc_1/uP_microblaze_0_axi_intc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_mdm_1_1/uP_mdm_1_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_mdm_1_1/uP_mdm_1_1_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_rst_mig_7series_0_83M_1/uP_rst_mig_7series_0_83M_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_rst_mig_7series_0_83M_1/uP_rst_mig_7series_0_83M_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_rst_mig_7series_0_83M_1/uP_rst_mig_7series_0_83M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_axi_uartlite_0_0/uP_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_axi_uartlite_0_0/uP_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_axi_uartlite_0_0/uP_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_axi_dma_0_0/uP_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_axi_dma_0_0/uP_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_axi_dma_0_0/uP_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_axis_data_fifo_0_0/uP_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_mig_7series_0_2/uP_mig_7series_0_2/user_design/constraints/uP_mig_7series_0_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_mig_7series_0_2/uP_mig_7series_0_2/user_design/constraints/uP_mig_7series_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_auto_pc_3/uP_auto_pc_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_auto_us_0/uP_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_auto_us_0/uP_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_auto_us_0/uP_auto_us_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_auto_us_1/uP_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_auto_us_1/uP_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_auto_us_1/uP_auto_us_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_auto_us_2/uP_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_auto_us_2/uP_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_auto_us_2/uP_auto_us_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_auto_us_3/uP_auto_us_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_auto_us_3/uP_auto_us_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_auto_us_3/uP_auto_us_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_auto_ds_0/uP_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_auto_ds_0/uP_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_auto_ds_0/uP_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_auto_pc_0/uP_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_auto_ds_1/uP_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_auto_ds_1/uP_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_auto_ds_1/uP_auto_ds_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_auto_pc_1/uP_auto_pc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_auto_ds_2/uP_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_auto_ds_2/uP_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_auto_ds_2/uP_auto_ds_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_auto_pc_2/uP_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/uP_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/miner/Documents/JIME/4toAnio/procom/trabajo_final/PROCOMfinal/LastDesign/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_microblaze_0_0/data/mb_bootloop_le.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top uP_wrapper -part xc7a35ticsg324-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef uP_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file uP_wrapper_utilization_synth.rpt -pb uP_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
