# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/PROCOM_FP/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_microblaze_0_axi_intc_1/uP_microblaze_0_axi_intc_1.xci
# IP: The module: 'uP_microblaze_0_axi_intc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/PROCOM_FP/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_microblaze_0_axi_intc_1/uP_microblaze_0_axi_intc_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'uP_microblaze_0_axi_intc_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/PROCOM_FP/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_microblaze_0_axi_intc_1/uP_microblaze_0_axi_intc_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'uP_microblaze_0_axi_intc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/PROCOM_FP/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_microblaze_0_axi_intc_1/uP_microblaze_0_axi_intc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uP_microblaze_0_axi_intc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/PROCOM_FP/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_microblaze_0_axi_intc_1/uP_microblaze_0_axi_intc_1.xci
# IP: The module: 'uP_microblaze_0_axi_intc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/PROCOM_FP/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_microblaze_0_axi_intc_1/uP_microblaze_0_axi_intc_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'uP_microblaze_0_axi_intc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/PROCOM_FP/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_microblaze_0_axi_intc_1/uP_microblaze_0_axi_intc_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'uP_microblaze_0_axi_intc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/PROCOM_FP/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_microblaze_0_axi_intc_1/uP_microblaze_0_axi_intc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uP_microblaze_0_axi_intc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
