/* This file is automatically generated based on your hardware design. */
#include "memory_config.h"

struct memory_range_s memory_ranges[] = {
	/* uP_i_microblaze_0_local_memory_dlmb_bram_if_cntlr_Mem memory will not be tested since application resides in the same memory */
	{
		"uP_i_mig_7series_0_memaddr",
		"uP_i_mig_7series_0",
		0x80000000,
		268435456,
	},
};

int n_memory_ranges = 1;
