# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/miner/Documents/JIME/4toAnio/procom/vivado_stuff/rtl_procom/top_board/Arty_Master.xdc

# Block Designs: bd/MicroGPIO/MicroGPIO.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroGPIO || ORIG_REF_NAME==MicroGPIO} -quiet] -quiet

# IP: bd/MicroGPIO/ip/MicroGPIO_clk_wiz_0_1/MicroGPIO_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroGPIO_clk_wiz_0_1 || ORIG_REF_NAME==MicroGPIO_clk_wiz_0_1} -quiet] -quiet

# IP: bd/MicroGPIO/ip/MicroGPIO_microblaze_0_1/MicroGPIO_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroGPIO_microblaze_0_1 || ORIG_REF_NAME==MicroGPIO_microblaze_0_1} -quiet] -quiet

# IP: bd/MicroGPIO/ip/MicroGPIO_dlmb_v10_1/MicroGPIO_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroGPIO_dlmb_v10_1 || ORIG_REF_NAME==MicroGPIO_dlmb_v10_1} -quiet] -quiet

# IP: bd/MicroGPIO/ip/MicroGPIO_ilmb_v10_1/MicroGPIO_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroGPIO_ilmb_v10_1 || ORIG_REF_NAME==MicroGPIO_ilmb_v10_1} -quiet] -quiet

# IP: bd/MicroGPIO/ip/MicroGPIO_dlmb_bram_if_cntlr_1/MicroGPIO_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroGPIO_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==MicroGPIO_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/MicroGPIO/ip/MicroGPIO_ilmb_bram_if_cntlr_1/MicroGPIO_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroGPIO_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==MicroGPIO_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/MicroGPIO/ip/MicroGPIO_lmb_bram_1/MicroGPIO_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroGPIO_lmb_bram_1 || ORIG_REF_NAME==MicroGPIO_lmb_bram_1} -quiet] -quiet

# IP: bd/MicroGPIO/ip/MicroGPIO_mdm_1_1/MicroGPIO_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroGPIO_mdm_1_1 || ORIG_REF_NAME==MicroGPIO_mdm_1_1} -quiet] -quiet

# IP: bd/MicroGPIO/ip/MicroGPIO_rst_clk_wiz_0_100M_1/MicroGPIO_rst_clk_wiz_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroGPIO_rst_clk_wiz_0_100M_1 || ORIG_REF_NAME==MicroGPIO_rst_clk_wiz_0_100M_1} -quiet] -quiet

# IP: bd/MicroGPIO/ip/MicroGPIO_axi_uartlite_0_1/MicroGPIO_axi_uartlite_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroGPIO_axi_uartlite_0_1 || ORIG_REF_NAME==MicroGPIO_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/MicroGPIO/ip/MicroGPIO_xbar_0/MicroGPIO_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroGPIO_xbar_0 || ORIG_REF_NAME==MicroGPIO_xbar_0} -quiet] -quiet

# IP: bd/MicroGPIO/ip/MicroGPIO_microblaze_0_axi_periph_1/MicroGPIO_microblaze_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroGPIO_microblaze_0_axi_periph_1 || ORIG_REF_NAME==MicroGPIO_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/MicroGPIO/ip/MicroGPIO_axi_gpio_0_1/MicroGPIO_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroGPIO_axi_gpio_0_1 || ORIG_REF_NAME==MicroGPIO_axi_gpio_0_1} -quiet] -quiet

# XDC: bd/MicroGPIO/MicroGPIO_ooc.xdc
