# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/miner/Documents/JIME/4toAnio/procom/vivado_stuff/MicroGPIO/MicroGPIO.srcs/sources_1/bd/MicroGPIO/ip/MicroGPIO_xbar_0/MicroGPIO_xbar_0.xci
# IP: The module: 'MicroGPIO_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/miner/Documents/JIME/4toAnio/procom/vivado_stuff/MicroGPIO/MicroGPIO.srcs/sources_1/bd/MicroGPIO/ip/MicroGPIO_xbar_0/MicroGPIO_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroGPIO_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/miner/Documents/JIME/4toAnio/procom/vivado_stuff/MicroGPIO/MicroGPIO.srcs/sources_1/bd/MicroGPIO/ip/MicroGPIO_xbar_0/MicroGPIO_xbar_0.xci
# IP: The module: 'MicroGPIO_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/miner/Documents/JIME/4toAnio/procom/vivado_stuff/MicroGPIO/MicroGPIO.srcs/sources_1/bd/MicroGPIO/ip/MicroGPIO_xbar_0/MicroGPIO_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroGPIO_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
