# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/miner/Documents/JIME/4toAnio/procom/vivado_stuff/MicroGPIO/MicroGPIO.srcs/sources_1/bd/MicroGPIO/ip/MicroGPIO_mdm_1_1/MicroGPIO_mdm_1_1.xci
# IP: The module: 'MicroGPIO_mdm_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/miner/Documents/JIME/4toAnio/procom/vivado_stuff/MicroGPIO/MicroGPIO.srcs/sources_1/bd/MicroGPIO/ip/MicroGPIO_mdm_1_1/MicroGPIO_mdm_1_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroGPIO_mdm_1_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/miner/Documents/JIME/4toAnio/procom/vivado_stuff/MicroGPIO/MicroGPIO.srcs/sources_1/bd/MicroGPIO/ip/MicroGPIO_mdm_1_1/MicroGPIO_mdm_1_1_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroGPIO_mdm_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/miner/Documents/JIME/4toAnio/procom/vivado_stuff/MicroGPIO/MicroGPIO.srcs/sources_1/bd/MicroGPIO/ip/MicroGPIO_mdm_1_1/MicroGPIO_mdm_1_1.xci
# IP: The module: 'MicroGPIO_mdm_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/miner/Documents/JIME/4toAnio/procom/vivado_stuff/MicroGPIO/MicroGPIO.srcs/sources_1/bd/MicroGPIO/ip/MicroGPIO_mdm_1_1/MicroGPIO_mdm_1_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroGPIO_mdm_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/miner/Documents/JIME/4toAnio/procom/vivado_stuff/MicroGPIO/MicroGPIO.srcs/sources_1/bd/MicroGPIO/ip/MicroGPIO_mdm_1_1/MicroGPIO_mdm_1_1_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroGPIO_mdm_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
