# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}

set_msg_config  -id {Vivado 12-3563}  -string {{ERROR: [Vivado 12-3563] The Nested sub-design 'C:/Users/asus/PROCOM2020/RUN/PROCOM_FP/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_mig_7series_0_0/uP_mig_7series_0_0.xci' can only be generated by its parent sub-design.}}  -suppress 

start_step write_bitstream
set ACTIVE_STEP write_bitstream
set rc [catch {
  create_msg_db write_bitstream.pb
  set_param chipscope.maxJobs 1
  open_checkpoint uP_wrapper_routed.dcp
  set_property webtalk.parent_dir C:/PROCOM_FP/PROCOM_FP.cache/wt [current_project]
  set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
  add_files c:/PROCOM_FP/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_microblaze_0_0/data/mb_bootloop_le.elf
  set_property SCOPED_TO_REF uP [get_files -all c:/PROCOM_FP/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_microblaze_0_0/data/mb_bootloop_le.elf]
  set_property SCOPED_TO_CELLS microblaze_0 [get_files -all c:/PROCOM_FP/PROCOM_FP.srcs/sources_1/bd/uP/ip/uP_microblaze_0_0/data/mb_bootloop_le.elf]
  catch { write_mem_info -force uP_wrapper.mmi }
  catch { write_bmm -force uP_wrapper_bd.bmm }
  write_bitstream -force uP_wrapper.bit 
  catch {write_debug_probes -quiet -force uP_wrapper}
  catch {file copy -force uP_wrapper.ltx debug_nets.ltx}
  close_msg_db -file write_bitstream.pb
} RESULT]
if {$rc} {
  step_failed write_bitstream
  return -code error $RESULT
} else {
  end_step write_bitstream
  unset ACTIVE_STEP 
}

